version: "3.8"
networks:
  lw:
    driver: bridge
services:
  db:
    image: mysql:latest
    container_name: mydb1
    networks: 
    - lw
    volumes: 
    - /data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=redhat
      - MYSQL_DATABASE=blogsdb
      - MYSQL_USER=tom
      - MYSQL_PASSWORD=redhat
  wp:
    depends_on: 
    - db
    image: wordpress:latest
    container_name: mywp1
    networks: 
    - lw
    ports:
    - 8080:80
    environment:
      - WORDPRESS_DB_HOST=mydb1
      - WORDPRESS_DB_USER=tom
      - WORDPRESS_DB_PASSWORD=redhat
      - WORDPRESS_DB_NAME=blogsdb
